# Gradle
org.gradle.daemon                    = true
org.gradle.jvmargs                   = -Xmx3G
org.gradle.parallel                  = true
org.gradle.caching                   = true
org.gradle.java.home                 = /usr/lib/jvm/java-25-openjdk
name                                 = Waypoints

# Common
java_version                         = 25
hytale_version                       = 0.+
manifestServerVersion                = >=0.5.0 <0.6.0
release_type                         = RELEASE
maven_url                            = https://maven.azuredoom.com/mods
hmod_maven_url                       = https://maven.hytalemodding.dev/releases
hmod_maven_snapshot_url              = https://maven.hytalemodding.dev/snapshots
maven_group_id                       = com.riprod
maven_artifact_id                    = waypointly

# Publishing
modtale_uuid                         = 0b6ee3a6-df34-4e93-b483-1e27fc4380bf
modifold_id                          = OPoaKw

# Mod options
group                                = com.riprod.waypointly
manifest_group                       = Riprod
mod_name                             = Waypointly
main_class                           = com.riprod.waypointly.Waypointly
mod_author                           = Riprod,Luisca
mod_id                               = Waypointly
mod_license                          = MIT
mod_description                      = Waypoints for Hytale
mod_credits                          = Riprod,Boffmedia
mod_logo                             = icon-256.png
mod_url                              = https://modtale.net/mod/Waypointly
mod_issues                           = https://github.com/itsriprod/Waypointly/issues
mod_sources                          = https://github.com/itsriprod/Waypointly
version                              = 2.1.0
includes_pack                        = true
disabled_by_default                  = false
patchline                            = release
load_user_mods                       = false
manifest_dependencies                =
manifest_opt_dependencies            =
curseforgeID                         = 1667204
